pseudo:
  name: "pseudo"
  enabled: true

workflow:
  max_worker: 20
  flow:
  - flow_name: "test_flow"
    event:
      - name: "test_event_1"
        async: true
      - name: "test_event_2"
        async: true
      - name: "test_event_3"
        async: true
      - name: "test_event_4"
        async: true
    start_event: "test_event_1"
    end_event: "test_event_4"
    transition:
       - from_event: "test_event_1"
         to_event: "test_event_2"
         expr: "event_1_done == true"
       - from_event: "test_event_2"
         to_event: "test_event_3"
         expr: "event_2_done == true"
       - from_event: "test_event_3"
         to_event: "test_event_4"
         expr: "event_3_done == true"